apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mw-db-pvc
  namespace: mw
spec:
  accessModes:
    - ReadWriteOnce # How many users can read/write. 
  resources:
    requests:
      storage: 1Gi 