apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mw-db-pvc
  namespace: mw
spec:
  accessModes:
    - ReadWriteOnce # This tells how many users can read/write or if it needs to be read only. 1 node mag het volume tegelijk mounten
  resources:
    requests:
      storage: 1Gi # How much storage we want, 1 gigabyte