apiVersion: v1
kind: ConfigMap
metadata:
  name: mw-db-init
  namespace: mw
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        name TEXT NOT NULL
    );

    INSERT INTO users (name) VALUES ('Maarten');