apiVersion: apps/v1
kind: Deployment
metadata:
  name: mw-db
  namespace: mw
  labels:
    app: mw-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mw-db
  template:
    metadata:
      labels:
        app: mw-db
    spec:
      containers:
        - name: postgres
          image: postgres:18.2
          ports:
            - containerPort: 5432
          envFrom: # Reference to 02-db-secret.yaml
            - secretRef:
                name: mw-db-secret

          volumeMounts: # Persistent storage for data
            - name: db-data
              mountPath: /var/lib/postgresql
            - name: db-init  # init.sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: mw-db-pvc
        - name: db-init
          configMap:
            name: mw-db-init