apiVersion: apps/v1
kind: Deployment
metadata:
  name: mw-api
  namespace: mw
  labels:
    app: mw-api
spec:
  replicas: 3 # 3 replicas to prove horizontal scaling and load-balancing
  selector:
    matchLabels:
      app: mw-api
  template:
    metadata:
      labels:
        app: mw-api
    spec:
      containers:
        - name: api
          image: mw-api:1.0
          imagePullPolicy: IfNotPresent  # makes sure the image is only downloaded when not locally present
          ports:
            - containerPort: 8000

# healthcheck that automatically restarts API when unhealthy

          livenessProbe:
            httpGet:
              path: /container
              port: 8000
            initialDelaySeconds: 10 # seconds to wait after container start before first check
            periodSeconds: 10 # interval
            timeoutSeconds: 2 # seconds to wait for a response
            failureThreshold: 3 # number of failed checks before K8s takes action
          readinessProbe:
            httpGet:
              path: /container
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mw-db-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mw-db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mw-db-secret
                  key: POSTGRES_PASSWORD