apiVersion: apps/v1
kind: Deployment
metadata:
  name: mw-web
  namespace: mw
  labels:
    app: mw-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mw-web
  template:
    metadata:
      labels:
        app: mw-web
    spec:
      containers:
        - name: web
          image: mw-web:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80